### ISSUE TITLE
Changing Plane to Car?

### ISSUE THREAD

**Issue by McNose** [basti0001/MMM-iHaveBeenThere#2]
Hi Basti,

this modul is really great. I like it personal and even the woman acceptance fakctor (WAF) is given:-)

You added the possibility of a trip, which is pretty cool. But most of our trips were by car; we just arrived by plane.
Is it possible to add a car on my own, if you give me a little hint? Otherwise it would be great if you can realize it in your next version.

Thank you.

**Comment by basti0001** [comment]
Hi McNose,
sry for my delayed answer. No notification from github.... 

Ok adding the symbol as a car is a nice feature. 
At present the plane is only a hard coded svg path in the module. 
Best way to implement your new feature in my kind of view would be to
1. Make svg path of the object a config parameter of module (still default can be the plane) 
2. Change namespacing from plane to something like AnimationObject
3. Create enable/disable scaling animation flag config parameter in module. During flight at present the plane is getting scaled a little bigger so we have the impression the plane gains some altitude. On e. g. a car this might look fuzzy. So depending on this parameter, the user can choose. 
4. Scaling factor of animation also shall be a parameter

Thats all from my kind of view. Any additional things I missed? 

Cheers

Sebastian

**Comment by McNose** [comment]
Hi Sebastian,

that sounds good to me.
I will give it a try and let you know if I have any problems.

Thanks a lot.

Cheers

McNose
