### ISSUE TITLE
Map moves up

### ISSUE THREAD

**Issue by JahFyahh** [basti0001/MMM-iHaveBeenThere#5]
Hi,

Is it normal that the world map moves up over time? After a reboot it looks ok again, but not sure if this is normal or an issue.

Kind regards,
Jah

**Comment by basti0001** [comment]
Hi Jah, 
for how long did you run the screen? To be honest, I currently deactivated the app on my mirror, since i ran out of display space. :-(

**Comment by The-Exterminator** [comment]
Great app, can you make it, so it be set to car and fly, so it world card set a car with the distinaton. ???

**Comment by bbasselgia** [comment]
Great App.   Is it possible to adjust the size of the map?   I'd like to see the entire map, only smaller.

**Comment by JahFyahh** [comment]
> Hi Jah, 
> for how long did you run the screen? To be honest, I currently deactivated the app on my mirror, since i ran out of display space. :-(

Sorry I missed your comment. I have removed the app as well. I have the pi on a cron that reboots every Sunday. I will test it again when I have some time. Will most likely also run out of display space after the past years of trips :-D

**Comment by JahFyahh** [comment]
It's been a while and I'm not using this anymore so closing the issue. Thank you for the work so far.
